sudo: false

language: python

matrix:
  include:
    - python: 3.5.2
      env: TEST_SUITE=test
    - python: 3.5.2
      env: TEST_SUITE=lint
    - python: 3.6-dev
      env: TEST_SUITE=test
    - python: 3.5
      env: TEST_SUITE=test
    - python: 3.4
      env: TEST_SUITE=test
    - python: 3.3
      env: TEST_SUITE=test

before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install: python setup.py -q install

script: ./check.sh "$TEST_SUITE"
