sudo: false
#addons:
#  apt_packages:
#    - pandoc

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pylint.d

matrix:
  include:
    - python: 3.5
      env: TEST_SUITE=test
    - python: 3.4
      env: TEST_SUITE=test
    - python: 3.5
      env: TEST_SUITE=lint

before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install:
  - pip install -r requirements.txt

script: ./run-tests.sh
#  - pandoc --from=markdown --to=rst README.md | diff DESCRIPTION.rst -

after_success: |
  if [ "${TEST_SUITE}" = "test" ]; then
    coveralls;
  fi
