sudo: false
addons:
  apt_packages:
    - pandoc

language: python
python:
  - 3.4
  - 3.5

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install:
  - pip install -r requirements.txt

script:
  - py.test --cov=mtg_ssm --strict -r w tests
  - pylint --rcfile=pylintrc *.py mtg_ssm
  - pylint --rcfile=pylintrc --disable=similarities tests
  - flake8 --ignore=E501,F401,F841 *.py mtg_ssm tests
#  - pandoc --from=markdown --to=rst README.md | diff DESCRIPTION.rst -

after_success:
  - coveralls
