sudo: false
addons:
  apt_packages:
    - pandoc

language: python

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.5
      env: TEST_SUITE=test
    - python: 3.4
      env: TEST_SUITE=test
    - python: 3.5
      env: TEST_SUITE=lint

before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install:
  - pip install -r requirements.txt

script: |
  if [ "${TEST_SUITE}" = "test" ]; then
    py.test --cov=mtg_ssm --strict -r w tests;
  elif [ "${TEST_SUITE}" = "lint" ]; then
    pylint --rcfile=pylintrc *.py mtg_ssm;
    pylint --rcfile=pylintrc --disable=similarities tests;
    flake8 --ignore=E501,F401,F841 *.py mtg_ssm tests;
  fi
#  - pandoc --from=markdown --to=rst README.md | diff DESCRIPTION.rst -

after_success: |
  if [ "${TEST_SUITE}" = "test" ]; then
    coveralls;
  fi
