sudo: false
addons:
  apt_packages:
    - pandoc

cache:
  directories:
    - $HOME/.cache/pip

language: python
python:
  - 3.4
  - 3.5

before_install:
  - pip install --upgrade pip pytest
  - pip install pylint flake8

script:
  - py.test --strict -r w tests
  - pylint --rcfile=pylintrc *.py mtg_ssm
  - pylint --rcfile=pylintrc --disable=similarities tests
  - flake8 --ignore=E501,F401,F841 *.py mtg_ssm tests
#  - pandoc --from=markdown --to=rst README.md | diff DESCRIPTION.rst -

notifications:
  email:
    - waksman@gmail.com
