sudo: false

language: python

matrix:
  include:
    - python: 3.5
      env: TEST_SUITE=test
    - python: 3.5
      env: TEST_SUITE=lint
    - python: 3.4
      env: TEST_SUITE=test
    - python: 3.3
      env: TEST_SUITE=test

before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install:
  - pip install -r requirements.txt

script: |
  if [ "${TEST_SUITE}" = "test" ]; then
    py.test --cov=mtg_ssm --strict -r w tests;
  elif [ "${TEST_SUITE}" = "lint" ]; then
    pylint --rcfile=pylintrc mtg_ssm &&
    pylint --rcfile=pylintrc --disable=similarities tests &&
    flake8 --max-complexity 10 --ignore=E501,F401,F841 *.py mtg_ssm tests;
  else
    error_without_calling_exit;
  fi
#  - pandoc --from=markdown --to=rst README.md | diff DESCRIPTION.rst -

after_success: |
  if [ "${TEST_SUITE}" = "test" ]; then
    coveralls;
  fi
