language: python
stages:
  - lint
  - test

cache: pip

before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install: python setup.py develop

script:
  - pytest tests/
  - coveralls

jobs:
  include:
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"

    - stage: lint
      python: "3.8.5"
      install:
        - pip install -r requirements.txt
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
      after_script: null
