sudo: false

language: python
python:
  - 3.5.2
  - 3.6-dev
  - 3.5
  - 3.4
  - 3.3

before_install:
  - pip install -U pip
  - pip install -U pytest

install: python setup.py develop

script:
  - python setup.py test
  - pylint mtg_ssm
  - pylint --disable=similarities,redefined-outer-name tests
  - flake8 --verbose --max-complexity 10 --ignore=E501,F401,F841
